# Generated by Django 3.1.4 on 2020-12-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/none/no0image.jpg', upload_to='Images/'),
        ),
    ]
